### ISSUE TITLE
Link to mailinglist broken

### ISSUE THREAD

**Issue by niccokunzmann** [chaoss/.github#3]
The profile/README.md (https://github.com/chaoss) has a link to the mailing list. When I visit https://lists.linuxfoundation.org/mailman/listinfo/chaoss, I see `No such list chaoss`. Do you still use a mailinglist?

**Comment by germonprez** [comment]
Thanks @niccokunzmann -- this has been fixed. We no longer use our mail list so it was removed from this page.
